# Generated by Django 4.2.11 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
